version: 2.1

jobs:
  hello-world-job:
    docker:
      - image: cimg/base:current
    steps:
      - run: echo "Hello, World!"
  goodnight-world-job:
    docker:
      - image: cimg/base:current
    steps:
      - run: echo "Goodnight, World!"

workflows:
  hello-world-workflow:
    jobs:
      - hello-world-job
      - goodnight-world-job
